name: CI

on:
  push:
    branches:
    - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: AlejandroSuero/selene-linter-action@v1.0.0
      with:
        # Github secret token
        token: ${{ secrets.GITHUB_TOKEN }}
        # selene arguments
        args: src/