name: CI

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Selene
        run: |
          wget https://github.com/jok-dev/selene/releases/download/0.29.1/selene-0.29.1-linux.zip
          unzip selene-0.29.1-linux.zip
          chmod +x selene
          sudo mv selene /usr/local/bin/

      - name: Run Selene
        id: selene
        continue-on-error: true
        run: |
          OUTPUT=$(selene src/ 2>&1)
          echo "$OUTPUT"
          echo 'SELENE_OUTPUT<<EOF' >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          if [ $? -ne 0 ]; then
            echo "SELENE_EXIT_CODE=1" >> $GITHUB_ENV
          else
            echo "SELENE_EXIT_CODE=0" >> $GITHUB_ENV
          fi

      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Selene Linter Report:**
            ```
            ${{ env.SELENE_OUTPUT }}
            ```

      - name: Check for Selene errors
        if: env.SELENE_EXIT_CODE != '0'
        run: exit 1